# Generated by Django 4.2.7 on 2024-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0018_task_success_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=['-stopped'],
                name='task_success_stopped_partial_idx',
                condition=models.Q(success=True),
            ),
        ),
    ]
